import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import { useLocation, useNavigate } from "react-router-dom";
import { useTheme } from "../../../context/ThemeContext";
import toast, { Toaster } from "react-hot-toast";

// Components
import MakerSidebar from "../../../components/PaperMaker/MakerSidebar/MakerSidebar";
import PaperPreview from "../../../components/PaperMaker/PaperPreview/PaperPreview";
import QuestionMenu from "../../../components/PaperMaker/QuestionMenu/QuestionMenu";
import PatternForm from "../../Admin/PaperPatterns/PatternForm";
import SavePaperModal from "../../../components/PaperMaker/SaveModal/SavePaperModal";
import ConfirmationModal from "../../../components/common/ConfirmationModal/ConfirmationModal";
import "./PaperMaker.css";
import "../../../layouts/UserLayout/UserLayout.css";

const PaperMaker = () => {
  const BASE_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:5000";
  const location = useLocation();
  const navigate = useNavigate();
  const { theme } = useTheme();

  // ✅ Exit Tracking
  const isExiting = useRef(false);

  // --- SESSION STATE ---
  const [sessionState, setSessionState] = useState(() => {
    if (location.state && location.state.isAutoGenerated) {
      return { data: location.state, menuOpen: true };
    }
    const savedData = localStorage.getItem("currentPaperData");
    const savedMenu = localStorage.getItem("isMenuOpen");
    if (savedData) {
      try {
        return {
          data: JSON.parse(savedData),
          menuOpen: savedMenu ? JSON.parse(savedMenu) : false,
        };
      } catch (e) {
        console.error("Error parsing data", e);
      }
    }
    return { data: location.state || null, menuOpen: true };
  });

  const [paperData, setPaperData] = useState(sessionState.data);
  const [isMenuOpen, setIsMenuOpen] = useState(sessionState.menuOpen);
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [showPatternEdit, setShowPatternEdit] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [saving, setSaving] = useState(false);
  const [isManualMode, setIsManualMode] = useState(false);
  const [deleteModal, setDeleteModal] = useState({
    isOpen: false,
    type: null,
    id: null,
    extra: null,
  });

  // --- EFFECTS ---
  useEffect(() => {
    if (!paperData) {
      navigate("/user/generate-paper");
    }
  }, [paperData, navigate]);

  useEffect(() => {
    if (paperData) {
      localStorage.setItem("currentPaperData", JSON.stringify(paperData));
    }
  }, [paperData]);

  useEffect(() => {
    localStorage.setItem("isMenuOpen", JSON.stringify(isMenuOpen));
  }, [isMenuOpen]);

  useEffect(() => {
    const handleBeforeUnload = (e) => {
      if (isExiting.current) return;
      if (paperData) {
        e.preventDefault();
        e.returnValue = "";
      }
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [paperData]);

  if (!paperData) return null;

  // --- HANDLERS ---
  const handleCancelPaper = () => {
    window.onbeforeunload = null;
    localStorage.removeItem("currentPaperData");
    localStorage.removeItem("paperSessionKey");
    localStorage.removeItem("isMenuOpen");
    navigate("/user/dashboard");
  };

  // ✅✅✅ FIXED: RELAXED MATCHING (Prevents Data Loss on Edit) ✅✅✅
  const handlePatternUpdate = (incomingData) => {
    if (!incomingData) {
      setShowPatternEdit(false);
      return;
    }

    const updatedPattern = incomingData.data || incomingData;
    if (!updatedPattern || !updatedPattern.sections) {
      toast.error("Failed to update pattern structure.");
      return;
    }

    setPaperData((prevData) => {
      const oldSections = prevData.selectedPattern?.sections || [];
      const newSections = updatedPattern.sections || [];

      const indexMap = {};
      const usedNewIndices = new Set();

      // --- MAPPING LOGIC ---
      oldSections.forEach((oldSec, oldIdx) => {
        const matchIdx = newSections.findIndex((newSec, newIdx) => {
          if (usedNewIndices.has(newIdx)) return false;

          // 🔥 RELAXED MATCHING: Sirf Type aur Marks match karo
          // Quantity (Limit) change hone par bhi ye TRUE rahega -> Sawal Delete NAHI honge
          const typeMatch = newSec.questionType === oldSec.questionType;
          const marksMatch = parseInt(newSec.marks) === parseInt(oldSec.marks);

          return typeMatch && marksMatch;
        });

        if (matchIdx !== -1) {
          indexMap[oldIdx] = matchIdx;
          usedNewIndices.add(matchIdx);
        }
      });

      // --- UPDATE QUESTIONS ---
      const updatedQuestions = prevData.questions
        .map((q) => {
          if (q.type === "MCQ") return q;
          if (!q.tabId) return q;

          let oldIdx = -1;

          if (q.tabId.startsWith("sec_")) {
            oldIdx = parseInt(q.tabId.replace("sec_", ""));
          } else if (q.tabId.startsWith("long_")) {
            const parts = q.tabId.split("_");
            oldIdx = parseInt(parts[1]);
          }

          // Agar purana section naye mein mil gaya (chahe quantity change ho gayi ho)
          if (oldIdx !== -1 && indexMap[oldIdx] !== undefined) {
            const newIdx = indexMap[oldIdx];

            // ID Update karo agar Index change hua hai
            if (newIdx !== oldIdx) {
              if (q.type === "SHORT") return { ...q, tabId: `sec_${newIdx}` };
              if (q.type === "LONG") {
                let suffix = "";
                if (q.tabId.endsWith("_a")) suffix = "_a";
                else if (q.tabId.endsWith("_b")) suffix = "_b";
                else if (q.tabId.endsWith("_full")) suffix = "_full";
                return { ...q, tabId: `long_${newIdx}${suffix}` };
              }
            }
            return q; // Same Index, Same Data -> KEEP IT
          }

          // Agar Section waqai DELETE ho gaya (Type/Marks match nahi huay), to remove karo
          return null;
        })
        .filter(Boolean);

      // --- TOTAL MARKS UPDATE ---
      const newTotalMarks =
        updatedPattern.totalMarks ||
        newSections.reduce((sum, sec) => {
          const qMarks = parseInt(sec.marks) || 0;
          const qQty = parseInt(sec.quantity || sec.totalQuestions) || 0;
          return sum + qMarks * qQty;
        }, 0);

      return {
        ...prevData,
        selectedPattern: updatedPattern,
        questions: updatedQuestions,
        totalMarks: newTotalMarks,
      };
    });

    setShowPatternEdit(false);
    toast.success("Pattern Updated Successfully!");
  };

  const handleAddQuestionsToPaper = (incomingQuestions, typeToUpdate) => {
    if (typeToUpdate === "REPLACE_ALL") {
      setPaperData((prevData) => ({
        ...prevData,
        questions: incomingQuestions,
      }));
      toast.success("Paper Updated Successfully!");
      return;
    }

    setPaperData((prevData) => {
      const existingQuestions = prevData.questions || [];
      const keepQuestions = existingQuestions.filter(
        (q) => q.type !== typeToUpdate,
      );
      const newFullList = [...keepQuestions, ...incomingQuestions];
      return { ...prevData, questions: newFullList };
    });
    if (incomingQuestions.length > 0)
      toast.success(`${typeToUpdate} Added Successfully!`);
    else toast(`${typeToUpdate} Cleared!`, { icon: "🗑️" });
  };

  const handlePrintPaper = (mode = "SINGLE") => {
    navigate("/user/print-paper", {
      state: { ...paperData, printSettings: { mode: mode } },
    });
  };

  const handleManualDelete = (qId) =>
    setDeleteModal({ isOpen: true, type: "SINGLE", id: qId, extra: null });
  const handleSectionDelete = (type, tabIdPrefix = null) =>
    setDeleteModal({
      isOpen: true,
      type: "SECTION",
      id: type,
      extra: tabIdPrefix,
    });

  const handleConfirmDelete = () => {
    const { type, id, extra } = deleteModal;
    setPaperData((prev) => {
      if (type === "SINGLE") {
        return {
          ...prev,
          questions: prev.questions.filter((q) => {
            const currentId = q.questionId?._id || q.questionId || q._id;
            return currentId !== id && q._id !== id;
          }),
        };
      }
      if (type === "SECTION") {
        return {
          ...prev,
          questions: prev.questions.filter((q) => {
            if (id === "MCQ" && q.type === "MCQ") return false;
            if (id === "LONG" && q.type === "LONG") return false;
            if (id === "SHORT" && q.type === "SHORT") {
              return extra ? !q.tabId?.startsWith(extra) : false;
            }
            return true;
          }),
        };
      }
      return prev;
    });
    setDeleteModal({ isOpen: false, type: null, id: null, extra: null });
    toast.success("Deleted successfully");
  };

  const handleManualUpdate = (qId, field, lang, value, optIndex = null) => {
    setPaperData((prev) => {
      const updatedQuestions = prev.questions.map((q) => {
        const id = q.questionId?._id || q.questionId || q._id;
        if (id === qId || q._id === qId) {
          if (field === "options" && optIndex !== null) {
            const newOpts = [...q.options];
            newOpts[optIndex] = { ...newOpts[optIndex], [lang]: value };
            return { ...q, options: newOpts };
          }
          if (field === "statement") {
            return { ...q, statement: { ...q.statement, [lang]: value } };
          }
        }
        return q;
      });
      return { ...prev, questions: updatedQuestions };
    });
  };

  const handleSaveClick = () => {
    if (!paperData.questions || paperData.questions.length === 0) {
      toast.error("Paper is empty! Please add questions first.");
      return;
    }
    setShowSaveModal(true);
  };

  const handleConfirmSave = async (paperTitle) => {
    setSaving(true);
    const token = localStorage.getItem("token");

    try {
      const questionsToSave = paperData.questions.map((q) => ({
        questionId: q.questionId?._id || q.questionId || q._id,
        statement: q.statement,
        type: q.type,
        options: q.options,
        marks: q.marks,
        tabId: q.tabId,
      }));

      const payload = {
        title: paperTitle,
        subject: paperData.subject?._id || paperData.subject,
        grade: paperData.grade,
        totalMarks: paperData.selectedPattern?.totalMarks || 0,
        pattern: paperData.selectedPattern,
        questions: questionsToSave,
        examLabel: paperData.examLabel || "",
        syllabusLabel: paperData.syllabusLabel || "",
        examDate: paperData.examDate || null,
      };

      let apiUrl = `${BASE_URL}/api/papers/save`;
      let method = "post";
      if (paperData._id && paperData.title === paperTitle) {
        apiUrl = `${BASE_URL}/api/papers/update/${paperData._id}`;
        method = "put";
      }

      const res = await axios[method](apiUrl, payload, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.data.success) {
        toast.success(method === "put" ? "Paper Updated!" : "Paper Saved!");
        isExiting.current = true;
        localStorage.removeItem("currentPaperData");
        localStorage.removeItem("paperSessionKey");
        localStorage.removeItem("isMenuOpen");
        navigate("/user/dashboard");
      }
    } catch (error) {
      console.error(error);
      toast.error(error.response?.data?.message || "Failed to save paper");
    } finally {
      setSaving(false);
      setShowSaveModal(false);
    }
  };

  return (
    <div
      className={`pm-container ${theme === "dark" ? "u-dark pw-dark" : "u-light pw-light"}`}
    >
      <Toaster
        position="top-center"
        reverseOrder={false}
        containerStyle={{ zIndex: 100000 }}
      />
      <MakerSidebar
        paperData={paperData}
        onOpenMenu={() => setIsMenuOpen(true)}
        isMenuOpen={isMenuOpen}
        isCollapsed={isSidebarCollapsed}
        toggleCollapse={() => setIsSidebarCollapsed(!isSidebarCollapsed)}
        onCancel={handleCancelPaper}
        onSave={handleSaveClick}
        onPrint={handlePrintPaper}
        isManualMode={isManualMode}
        toggleManualMode={() => setIsManualMode(!isManualMode)}
      />
      <div className="pm-workspace">
        <PaperPreview
          paperData={paperData}
          onOpenMenu={() => setIsMenuOpen(true)}
          isManualMode={isManualMode}
          onManualUpdate={handleManualUpdate}
          onManualDelete={handleManualDelete}
          onSectionDelete={handleSectionDelete}
        />
      </div>
      <QuestionMenu
        isOpen={isMenuOpen}
        onClose={() => setIsMenuOpen(false)}
        paperData={paperData}
        isSidebarCollapsed={isSidebarCollapsed}
        onEditPattern={() => setShowPatternEdit(true)}
        onAddQuestionsToPaper={handleAddQuestionsToPaper}
        selectedQuestions={paperData.questions || []}
      />
      {showPatternEdit && (
        <div className="pm-modal-overlay">
          <div className="pm-modal-content">
            <PatternForm
              onClose={() => setShowPatternEdit(false)}
              initialData={paperData.selectedPattern}
              isUserMode={true}
              onSuccess={handlePatternUpdate}
            />
          </div>
        </div>
      )}
      <SavePaperModal
        isOpen={showSaveModal}
        onClose={() => setShowSaveModal(false)}
        onConfirm={handleConfirmSave}
        isSaving={saving}
        defaultTitle={
          paperData.title === "Untitled Paper" ? "" : paperData.title
        }
      />
      <ConfirmationModal
        isOpen={deleteModal.isOpen}
        onClose={() => setDeleteModal({ isOpen: false, type: null, id: null })}
        onConfirm={handleConfirmDelete}
        title={
          deleteModal.type === "SECTION"
            ? "Delete Entire Section?"
            : "Delete Question?"
        }
        message={
          deleteModal.type === "SECTION"
            ? "Are you sure you want to remove all questions in this section?"
            : "Are you sure you want to remove this question?"
        }
        confirmText="Yes, Delete"
        cancelText="Cancel"
        isDanger={true}
      />
    </div>
  );
};

export default PaperMaker;
