import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import { useLocation, useNavigate } from "react-router-dom";
import { useTheme } from "../../../context/ThemeContext";
import toast, { Toaster } from "react-hot-toast";

// Components
import MakerSidebar from "../../../components/PaperMaker/MakerSidebar/MakerSidebar";
import PaperPreview from "../../../components/PaperMaker/PaperPreview/PaperPreview";
import QuestionMenu from "../../../components/PaperMaker/QuestionMenu/QuestionMenu";
import PatternForm from "../../Admin/PaperPatterns/PatternForm";
import ConfirmationModal from "../../../components/common/ConfirmationModal/ConfirmationModal";
import SavePaperModal from "../../../components/common/SavePaperModal/SavePaperModal";

import "./PaperMaker.css";
import "../../../layouts/UserLayout/UserLayout.css";

const PaperMaker = () => {
  const BASE_URL = import.meta.env.VITE_BACKEND_URL || "http://localhost:5000";
  const location = useLocation();
  const navigate = useNavigate();
  const { theme } = useTheme();

  // ✅ Intentional Exit Track karne ke liye
  const isExiting = useRef(false);

  // --- STATE INITIALIZATION ---
  const [paperData, setPaperData] = useState(() => {
    if (location.state && location.state.isAutoGenerated) return location.state;
    const savedData = localStorage.getItem("currentPaperData");
    return savedData ? JSON.parse(savedData) : location.state || null;
  });

  const [isMenuOpen, setIsMenuOpen] = useState(() => {
    const saved = localStorage.getItem("isMenuOpen");
    return saved ? JSON.parse(saved) : true;
  });

  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [showPatternEdit, setShowPatternEdit] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isManualMode, setIsManualMode] = useState(false);

  const [deleteModal, setDeleteModal] = useState({
    isOpen: false,
    type: null,
    id: null,
    extra: null,
  });

  // --- LOCAL STORAGE SYNC ---
  useEffect(() => {
    if (paperData)
      localStorage.setItem("currentPaperData", JSON.stringify(paperData));
  }, [paperData]);

  useEffect(() => {
    localStorage.setItem("isMenuOpen", JSON.stringify(isMenuOpen));
  }, [isMenuOpen]);

  // --- PREVENT ACCIDENTAL RELOAD ---
  useEffect(() => {
    const handleBeforeUnload = (e) => {
      // Agar Exit Mode ON hai, to roko mat
      if (paperData && !isExiting.current) {
        e.preventDefault();
        e.returnValue = "";
      }
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [paperData]);

  useEffect(() => {
    if (!paperData) navigate("/user/generate-paper");
  }, [paperData, navigate]);

  if (!paperData) return null;

  // ==========================================
  // 🔥 FIXED HANDLERS
  // ==========================================

  // 1. Cancel Click -> Open Custom Modal
  const handleCancelPaper = () => {
    setDeleteModal({
      isOpen: true,
      type: "CANCEL_PAPER",
      id: null,
      extra: null,
    });
  };

  // 2. Confirm Action
  const handleConfirmAction = () => {
    const { type, id, extra } = deleteModal;

    // A. DISCARD PAPER (Exit Logic)
    if (type === "CANCEL_PAPER") {
      isExiting.current = true; // ✅ Browser alert kill
      window.onbeforeunload = null; // ✅ Double safety

      localStorage.removeItem("currentPaperData");
      localStorage.removeItem("isMenuOpen");

      // Note: Hum yahan setDeleteModal(false) NAHI kar rahe
      // kyunke hum page chor ke ja rahe hain.
      // State update karne se race condition ho sakti hai.

      navigate("/user/dashboard");
      return;
    }

    // B. DELETE QUESTION / SECTION
    setPaperData((prev) => {
      const questions = prev.questions.filter((q) => {
        const qId = q.questionId?._id || q.questionId || q._id;
        if (type === "SINGLE") return qId !== id && q._id !== id;
        if (type === "SECTION") {
          if (id === "MCQ" && q.type === "MCQ") return false;
          if (id === "LONG" && q.type === "LONG") return false;
          if (id === "SHORT" && q.type === "SHORT")
            return extra ? !q.tabId?.startsWith(extra) : false;
        }
        return true;
      });
      return { ...prev, questions };
    });

    // Close Modal after delete
    setDeleteModal({ isOpen: false, type: null, id: null, extra: null });
    toast.success("Deleted successfully");
  };

  // --- OTHER HANDLERS ---
  const handlePatternUpdate = (updatedPattern) => {
    if (!updatedPattern || !updatedPattern.sections) {
      toast.error("Failed to update pattern structure.");
      return;
    }
    setPaperData((prevData) => ({
      ...prevData,
      selectedPattern: updatedPattern,
    }));
    setShowPatternEdit(false);
    toast.success("Pattern Updated Successfully!");
  };

  const handleAddQuestionsToPaper = (incomingQuestions, typeToUpdate) => {
    if (typeToUpdate === "REPLACE_ALL") {
      setPaperData((prevData) => ({
        ...prevData,
        questions: incomingQuestions,
      }));
      toast.success("Paper Updated Successfully!");
      return;
    }
    setPaperData((prevData) => {
      const existingQuestions = prevData.questions || [];
      const keepQuestions = existingQuestions.filter(
        (q) => q.type !== typeToUpdate,
      );
      return {
        ...prevData,
        questions: [...keepQuestions, ...incomingQuestions],
      };
    });
    if (incomingQuestions.length > 0)
      toast.success(`${typeToUpdate} Added Successfully!`);
    else toast(`${typeToUpdate} Cleared!`, { icon: "🗑️" });
  };

  const handlePrintPaper = (mode = "SINGLE") => {
    navigate("/user/print-paper", {
      state: { ...paperData, printSettings: { mode: mode } },
    });
  };

  const handleManualDelete = (qId) =>
    setDeleteModal({ isOpen: true, type: "SINGLE", id: qId, extra: null });
  const handleSectionDelete = (type, tabIdPrefix = null) =>
    setDeleteModal({
      isOpen: true,
      type: "SECTION",
      id: type,
      extra: tabIdPrefix,
    });

  const handleManualUpdate = (qId, field, lang, value, optIndex = null) => {
    setPaperData((prev) => {
      const updatedQuestions = prev.questions.map((q) => {
        const id = q.questionId?._id || q.questionId || q._id;
        if (id === qId || q._id === qId) {
          if (field === "options") {
            const newOpts = [...q.options];
            newOpts[optIndex] = { ...newOpts[optIndex], [lang]: value };
            return { ...q, options: newOpts };
          }
          if (field === "statement") {
            return { ...q, statement: { ...q.statement, [lang]: value } };
          }
        }
        return q;
      });
      return { ...prev, questions: updatedQuestions };
    });
  };

  // Save Logic
  const handleSaveClick = () => {
    if (!paperData.questions || paperData.questions.length === 0) {
      toast.error("Paper is empty!");
      return;
    }
    setShowSaveModal(true);
  };

  const handleConfirmSave = async (paperTitle) => {
    setIsSaving(true);
    const token = localStorage.getItem("token");

    try {
      const questionsToSave = paperData.questions.map((q) => ({
        questionId: q.questionId?._id || q.questionId || q._id,
        statement: q.statement,
        type: q.type,
        options: q.options,
        marks: q.marks,
        tabId: q.tabId,
      }));

      const payload = {
        title: paperTitle,
        subject: paperData.subject?._id || paperData.subject,
        grade: paperData.grade,
        totalMarks: paperData.selectedPattern?.totalMarks || 0,
        pattern: paperData.selectedPattern,
        questions: questionsToSave,
        examLabel: paperData.examLabel || "",
        syllabusLabel: paperData.syllabusLabel || "",
        examDate: paperData.examDate || null,
      };

      let apiUrl = `${BASE_URL}/api/papers/save`;
      let method = "post";
      if (paperData._id && paperData.title === paperTitle) {
        apiUrl = `${BASE_URL}/api/papers/update/${paperData._id}`;
        method = "put";
      }

      const res = await axios[method](apiUrl, payload, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.data.success) {
        toast.success(method === "put" ? "Paper Updated!" : "Paper Saved!");
        isExiting.current = true; // ✅ Allow Exit
        localStorage.removeItem("currentPaperData");
        setShowSaveModal(false);
        navigate("/user/dashboard");
      }
    } catch (error) {
      console.error(error);
      toast.error(error.response?.data?.message || "Failed to save paper");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div
      className={`pm-container ${theme === "dark" ? "u-dark pw-dark" : "u-light pw-light"}`}
    >
      <Toaster
        position="top-center"
        reverseOrder={false}
        containerStyle={{ zIndex: 100000 }}
      />

      <MakerSidebar
        paperData={paperData}
        onOpenMenu={() => setIsMenuOpen(true)}
        isMenuOpen={isMenuOpen}
        isCollapsed={isSidebarCollapsed}
        toggleCollapse={() => setIsSidebarCollapsed(!isSidebarCollapsed)}
        onCancel={handleCancelPaper}
        onSave={handleSaveClick}
        onPrint={handlePrintPaper}
        isManualMode={isManualMode}
        toggleManualMode={() => setIsManualMode(!isManualMode)}
      />

      <div className="pm-workspace">
        <PaperPreview
          paperData={paperData}
          onOpenMenu={() => setIsMenuOpen(true)}
          isManualMode={isManualMode}
          onManualUpdate={handleManualUpdate}
          onManualDelete={handleManualDelete}
          onSectionDelete={handleSectionDelete}
        />
      </div>

      <QuestionMenu
        isOpen={isMenuOpen}
        onClose={() => setIsMenuOpen(false)}
        paperData={paperData}
        isSidebarCollapsed={isSidebarCollapsed}
        onEditPattern={() => setShowPatternEdit(true)}
        onAddQuestionsToPaper={handleAddQuestionsToPaper}
        selectedQuestions={paperData.questions || []}
      />

      {showPatternEdit && (
        <div className="pm-modal-overlay">
          <div className="pm-modal-content">
            <PatternForm
              onClose={() => setShowPatternEdit(false)}
              initialData={paperData.selectedPattern}
              isUserMode={true}
              onSuccess={handlePatternUpdate}
            />
          </div>
        </div>
      )}

      <SavePaperModal
        isOpen={showSaveModal}
        onClose={() => setShowSaveModal(false)}
        onConfirm={handleConfirmSave}
        isSaving={isSaving}
        defaultTitle={
          paperData.title === "Untitled Paper" ? "" : paperData.title
        }
      />

      {/* ✅ UNIFIED CONFIRMATION MODAL */}
      <ConfirmationModal
        isOpen={deleteModal.isOpen}
        onClose={() => setDeleteModal({ isOpen: false, type: null, id: null })}
        onConfirm={handleConfirmAction}
        title={
          deleteModal.type === "CANCEL_PAPER"
            ? "Discard & Exit?"
            : deleteModal.type === "SECTION"
              ? "Delete Section?"
              : "Delete Question?"
        }
        message={
          deleteModal.type === "CANCEL_PAPER"
            ? "Unsaved changes will be lost. Do you want to leave?"
            : deleteModal.type === "SECTION"
              ? "Remove all questions in this section?"
              : "Remove this question?"
        }
        confirmText={
          deleteModal.type === "CANCEL_PAPER" ? "Discard & Leave" : "Delete"
        }
        cancelText="Cancel"
        isDanger={true}
      />
    </div>
  );
};

export default PaperMaker;
